apiVersion: v1
kind: Service
metadata:
  name: server-svc
  labels:
    app: ingress-default-backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: ingress-default-backend
