apiVersion: v1
kind: Service
metadata:
  name: custom-default-backend
  labels:
    app.kubernetes.io/name: custom-default-backend
spec:
  selector:
    app.kubernetes.io/name: custom-default-backend
  ports:
  - port: 80
    targetPort: 80
    name: http